import type { Settings } from './schema'
import { BUNDLED_LOCAL_MODEL_ID, METIS_WORKER_URL } from './schema'
import { DEFAULT_PERMISSION_STATE } from './permission-state'

export const DEFAULT_SETTINGS: Settings = {
  provider: 'cloudflare', // keep in lockstep with BaseSettingsSchema's ProviderIdSchema default above
  providerPriority: 'api',
  providerFallbackOrder: [],
  providerModels: {},
  providerModelsThinking: {},
  providerModelsDeep: {},
  providerModelsSpotlightRef: {},
  routingMode: 'auto',
  resilience: { preferFreeOnExhaustion: true, budgetPreempt: true, hedge: true },
  thinkingMode: 'auto',
  askFollowUpMemory: false,
  askCaveman: 'full',
  customBaseUrl: '',
  cloudflareBaseUrl: METIS_WORKER_URL,
  dustWorkspaceId: '',
  dustBaseUrl: 'https://dust.tt',
  dustSessionOrigin: 'oauth',
  azureClientId: '',
  azureTenantId: '',
  azureAllowedDomain: '',
  graphifyEnabled: true,
  graphifyAutoRebuild: true,
  graphifyBackend: 'auto',
  outputLanguage: 'auto',
  summaryLanguage: 'auto',
  encryptTranscripts: true,
  publishBrainPages: false,
  transcriptRetentionDays: 0,
  systemPrompt:
    'You are Métis, a fast, sharp desktop assistant living in an always-on overlay. ' +
    'Answer concisely and directly in clean markdown. Lead with the answer. Use code blocks ' +
    'with language tags, KaTeX for math ($...$), and tables when they help. No filler.',
  modePrompts: {},
  contextDocs: {},
  customModes: [],
  meetingNotifications: false,
  temperature: 0.4,
  contentProtection: true,
  privateView: false,
  audioSource: 'both',
  micDeviceId: '',
  suggestEverySec: 8,
  mode: 'general',
  profile: { name: '', role: '', company: '', resume: '', jobDescription: '', notes: '' },
  shortcuts: {}, // empty → built-in DEFAULT_SHORTCUTS apply (merged at hotkey registration)
  autoSuggest: true,
  screenAsk: true,
  showLiveTranscript: false,
  meetingsFolder: '',
  teamTranscriptFolders: [],
  autoSaveTranscripts: false,
  launchAtLogin: false,
  onboardingDone: false,
  onboardingDoneAt: 0,
  recordingConsent: false,
  playListenChime: true,
  soundCues: true,
  uiSounds: true,
  quickActionsRainbow: true,
  instantSuggestions: true,
  backgroundScreenContext: false,
  overlayOpacity: 1,
  autoHideOverlay: true,
  overlayLayout: 'hide',
  overlayOrbStyle: 'jakub',
  overlayPlacement: 'top-center',
  overlayRightEdgeYByDisplay: {},
  overlayRightEdgeAnchorByDisplay: {},
  showFullTranscriptInReview: false,
  asrQuality: 'best',
  asrEngine: 'parakeet',
  enterpriseLive: { managed: false, inferenceMode: 'legacy', summaryOnly: false },
  cloudSttProvider: 'unconfigured',
  cfAiGatewayId: '',
  cloudflareAccountId: '',
  asrLanguage: 'auto',
  asrLastFallbackAt: null,
  asrWebgpuFallbackAt: null,
  micOnlyFallbackAt: null,
  requireConsentIndicator: true,
  redactSensitive: true,
  lastConsentReminderAt: 0,
  asrCorrections: [],
  asrEntityBias: true,
  cliConnected: {},
  lastClickedCli: null,
  dustTokenMintedAt: 0,
  cliNoticeAck: false,
  mcpConnections: [],
  clickupClientId: '',
  planeClientId: '',
  localLlm: {
    enabled: false,
    modelId: BUNDLED_LOCAL_MODEL_ID,
    useFor: { suggest: false, summary: false, vision: false },
    fallback: false
  },
  speakerId: { enabled: true, saveVoiceprints: false },
  brainConsolidation: { enabled: true, maxPassesPerDay: 2, preferLocal: false },
  usageStats: { meetingsSummarized: 0, conversationMinutes: 0, firstMeetingAt: 0 },
  timeSaved: { writeupRatio: 0.2, floorMin: 5, capMin: 30 },
  tapControl: {
    enabled: false,
    armOnlyWhileListening: true,
    sensitivity: 0.5,
    zoneActions: [],
    profile: null
  },
  licenseServerUrl: '',
  licenseKey: '',
  licenseCompanyName: '',
  licenseSeatCap: 0,
  licenseExpiresAt: null,
  licenseValid: false,
  licenseLastValidatedAt: 0,
  licenseGateEnabled: false,
  licenseLease: '',
  trialStartedAt: null,
  operatorUrl: '',
  operatorIngestSecret: '',
  sendAskText: false,
  operatorLicenseToken: '',
  operatorLicenseJti: '',
  operatorLicenseLast4: '',
  operatorLicenseExpiresAt: null,
  operatorTier: null,
  operatorEntitlements: null,
  operatorIntegrationsVersion: 0,
  operatorEntitlementsAt: 0,
  permissionState: DEFAULT_PERMISSION_STATE
}
