import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { overlayAllowsMinimize, overlayDocksBarCircle, overlayShowsBarOrb, shouldForceParkOnBecameIdle } from '@shared/overlay-chrome'
import { BAR_PILL_HEIGHT_PX, BAR_PILL_SIZE_PX, BAR_PILL_WIDTH_PX, ORB_MOODS, ORB_STATE, orbBoxForMood } from './lib/bar-pill-orb'

const root = join(__dirname)
const app = readFileSync(join(root, 'App.tsx'), 'utf8').replace(/\r\n/g, '\n')
const pill = readFileSync(join(root, 'components', 'ControlPill.tsx'), 'utf8').replace(/\r\n/g, '\n')
const orbBtn = readFileSync(join(root, 'components', 'JarvisOrbButton.tsx'), 'utf8').replace(/\r\n/g, '\n')
const bar = readFileSync(join(root, 'components', 'Bar.tsx'), 'utf8').replace(/\r\n/g, '\n')
const css = readFileSync(join(root, 'styles.css'), 'utf8').replace(/\r\n/g, '\n')
const peek = readFileSync(join(root, 'components', 'OverlayPeek.tsx'), 'utf8').replace(/\r\n/g, '\n')
const index = readFileSync(join(__dirname, '../../main/index.ts'), 'utf8').replace(/\r\n/g, '\n')
const geometry = readFileSync(join(__dirname, '../../main/island/geometry.ts'), 'utf8').replace(/\r\n/g, '\n')
const watch = readFileSync(join(__dirname, '../../main/island/cursor-watch.ts'), 'utf8').replace(/\r\n/g, '\n')
const contract = readFileSync(join(__dirname, '../../../docs/design/BAR-PILL.md'), 'utf8')
const orb = readFileSync(join(root, 'lib', 'bar-pill-orb.ts'), 'utf8')

describe('BAR-PILL contract', () => {
  it('minimize-to-circle is bar-only', () => {
    expect(overlayAllowsMinimize('bar')).toBe(true)
    expect(overlayAllowsMinimize('hide')).toBe(false)
    expect(overlayAllowsMinimize('island')).toBe(false)
    expect(contract).toMatch(/overlayAllowsMinimize\(layout\) === \(layout === 'bar'\)/)
    expect(contract).toMatch(/overlayShowsBarOrb\(layout, minimized\) === \(layout === 'bar' && minimized\)/)
    expect(contract).toMatch(/overlayDocksBarCircle\(layout\) === \(layout === 'bar'\)/)
    expect(bar).toMatch(/canMinimize\?: boolean/)
    expect(bar).toMatch(/JarvisOrbButton/)
    expect(bar).toMatch(/Minimize to the orb/)
    expect(bar).not.toMatch(/<Minimize2/)
    expect(app).toMatch(/canMinimize=\{canMinimize\}/)
    expect(app).toMatch(/if \(!overlayAllowsMinimize\(overlayLayout\)\) return/)
    expect(app).toMatch(/overlayShowsBarOrb\(overlayLayout, minimized\)/)
    expect(app).toMatch(/shouldForceParkOnBecameIdle/)
    expect(app).toMatch(/collapse-now/)
    expect(shouldForceParkOnBecameIdle({ becameIdle: true, usesHover: true })).toBe(true)
    expect(index).toMatch(/if \(narrow && !overlayAllowsMinimize\(liveOverlayLayout\(\)\)\) return/)
    expect(app).not.toMatch(/overlayLayout:\s*'bar'/)
    expect(app).not.toMatch(/overlayLayout:\s*"bar"/)
  })

  it('visibility matches the bar: Hide/Island never show the circle; Bar expanded hides it', () => {
    expect(overlayShowsBarOrb('hide', false)).toBe(false)
    expect(overlayShowsBarOrb('hide', true)).toBe(false)
    expect(overlayShowsBarOrb('island', false)).toBe(false)
    expect(overlayShowsBarOrb('island', true)).toBe(false)
    expect(overlayShowsBarOrb('bar', false)).toBe(false)
    expect(overlayShowsBarOrb('bar', true)).toBe(true)
    expect(overlayDocksBarCircle('bar')).toBe(true)
    expect(overlayDocksBarCircle('hide')).toBe(false)
    expect(overlayDocksBarCircle('island')).toBe(false)
    expect(app).toMatch(/showBarOrb \? \(/)
    expect(app).toMatch(/<ControlPill/)
    expect(peek).not.toMatch(/ControlPill|data-bar-pill-orb|ThinkingOrb/)
    expect(bar).toMatch(/data-bar-pill-orb|JarvisOrbButton/)
    const pillMounts = app.split('<ControlPill').length - 1
    expect(pillMounts).toBe(1)
  })

  it('bar+minimized renders the fixed thinking-orb circle', () => {
    expect(pill).toMatch(/JarvisOrbButton/)
    expect(orbBtn).toMatch(/data-bar-pill-orb/)
    expect(orbBtn).toMatch(/ThinkingOrb/)
    expect(orbBtn).toMatch(/pillClickShouldExpand/)
    expect(pill).toMatch(/orbMood/)
    expect(css).toMatch(/\.aw-orb/)
    expect(css).not.toMatch(/bar-pill-spring-in/)
    expect(css).not.toMatch(/scale\(0\.88\)/)
    expect(BAR_PILL_WIDTH_PX).toBe(BAR_PILL_HEIGHT_PX)
    expect(BAR_PILL_SIZE_PX).toBe(64)
    expect(css).toMatch(/\.aw-orb \{[\s\S]*?width:\s*64px/)
    expect(css).toMatch(/\.aw-orb \{[\s\S]*?height:\s*64px/)
    expect(css).toMatch(/\.aw-orb \{[\s\S]*?border-radius:\s*50%/)
    expect(css).toMatch(/\.aw-orb \{[\s\S]*?background:\s*transparent/)
    expect(css).toMatch(/\.aw-orb__canvas \{[\s\S]*?width:\s*64px/)
    expect(css).toMatch(/\.aw-orb__canvas \{[\s\S]*?height:\s*64px/)
    expect(css).toMatch(/\.aw-orb__canvas \{[\s\S]*?border-radius:\s*0/)
  })

  it('never flattens: thinking-orb circle, same scale on X and Y', () => {
    expect(orb).not.toMatch(/fibonacciCapsule/)
    expect(orb).not.toMatch(/p\.x \* 0\.42,\s*p\.y \* 0\.88/)
    expect(orb).not.toMatch(/SPHERE_VS/)
    expect(orb).not.toMatch(/SPHERE_FS/)
    expect(orb).not.toMatch(/getContext\(\s*['"]webgl/)
    expect(orb).not.toMatch(/WebGLRenderingContext/)
    expect(orb).toMatch(/idle: 'solving'/)
    expect(orb).toMatch(/thinking: 'working'/)
    expect(css).toMatch(/data-orb-mood='idle'/)
    expect(css).not.toMatch(/\.aw-orb\[data-orb-mood='idle'\] \{[\s\S]*?radial-gradient/)
    expect(css).not.toMatch(/\.aw-orb__rec \{[\s\S]*?background:\s*#f0717a/)
    for (const mood of ORB_MOODS) {
      const box = orbBoxForMood(mood)
      expect(box.width).toBe(BAR_PILL_SIZE_PX)
      expect(box.height).toBe(BAR_PILL_SIZE_PX)
    }
  })

  it('click expands and drag does not', () => {
    expect(orbBtn).toMatch(/onClick=\{\(\) => \{/)
    expect(orbBtn).toMatch(/pillClickShouldExpand\(dragMovedRef\.current\)/)
    expect(orbBtn).toMatch(/useWindowDrag/)
  })

  it('hide and island rest sizes and hover math stay put', () => {
    expect(geometry).toMatch(/export const OVERLAY_HIDE_PARK = \{ width: 8, height: 2 \}/)
    expect(geometry).toMatch(/export const OVERLAY_ISLAND_PEEK = \{ width: 132, height: 15 \}/)
    expect(css).toMatch(/\.overlay-hide-target \{[\s\S]*?width:\s*8px/)
    expect(css).toMatch(/\.overlay-hide-target \{[\s\S]*?height:\s*2px/)
    expect(css).toMatch(/\.overlay-peek \{[\s\S]*?width:\s*132px/)
    expect(css).toMatch(/\.overlay-peek \{[\s\S]*?height:\s*15px/)
    expect(peek).toMatch(/overlay-hide-target/)
    expect(watch).toMatch(/decideCursorWatch/)
    expect(watch).toMatch(/overlayUsesHover/)
    expect(index).toMatch(/const BAR_MIN_HEIGHT = 44/)
  })

  it('uses the real thinking-orbs package, not WebGL or a Fit Studio core', () => {
    expect(pill).not.toMatch(/unpkg/)
    expect(app).not.toMatch(/unpkg/)
    expect(orb).not.toMatch(/unpkg\.com/)
    expect(orb).not.toMatch(/cdn\.jsdelivr/)
    expect(orb).not.toMatch(/spline\.design/)
    expect(orb).not.toMatch(/JARVIS_ORB_POINTS/)
    expect(orb).not.toMatch(/fibonacciSphere/)
    expect(orb).not.toMatch(/electronCountForMood/)
    expect(orb).not.toMatch(/FIT_STUDIO/)
    expect(orb).not.toMatch(/idle: 0x7f00da/)
    expect(orb).not.toMatch(/idle: 0x4ca8e8/)
    expect(orb).not.toMatch(/idle: 0xb266e9/)
    expect(orbBtn).toMatch(/from 'thinking-orbs'/)
    expect(orbBtn).toMatch(/theme=\{BAR_ORB_THEME\}/)
    expect(orbBtn).toMatch(/size=\{BAR_PILL_SIZE_PX\}/)
    expect(orbBtn).toMatch(/aria-label=""/)
    expect(orbBtn).not.toMatch(/Solving…/)
    expect(orb).toMatch(/orbHostPaintsText/)
    expect(ORB_STATE.idle).toBe('solving')
    expect(ORB_STATE.thinking).toBe('working')
    expect(ORB_STATE.factcheck).toBe('searching')
    expect(ORB_STATE.connecting).toBe('connecting')
  })

  it('QUALITY hats: idle bar has no orb rAF; no custom WebGL loop', () => {
    const quality = readFileSync(join(__dirname, '../../../docs/design/QUALITY.md'), 'utf8')
    expect(quality).toMatch(/## Motion/)
    expect(quality).toMatch(/## Interaction/)
    expect(quality).toMatch(/## Performance/)
    expect(quality).toMatch(/## Visual/)
    expect(quality).toMatch(/## Stability/)
    expect(quality).toMatch(/REJECT/)
    expect(orb).toMatch(/shouldRunOrbRaf/)
    expect(orb).not.toMatch(/getUniformLocation/)
    expect(orb).not.toMatch(/gl\.drawArrays/)
    expect(orbBtn).not.toMatch(/getBoundingClientRect/)
    expect(css).toMatch(/\.aw-orb \{[\s\S]*?border-radius:\s*50%/)
    expect(app).toMatch(/showBarOrb/)
    expect(app).not.toMatch(/ThinkingOrb/)
    expect(css).toMatch(/overlay-chrome-diagram__orb/)
    expect(orbBtn).toMatch(/data-orb-listening/)
    expect(orbBtn).toMatch(/shouldShowOrbRecDot/)
    expect(orb).toMatch(/shouldShowOrbRecDot/)
    expect(orb).not.toMatch(/REC_DOT_COLOR/)
  })
})
