import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { OVERLAY_ORB_COPY, OVERLAY_ORB_PICKER_CARDS, OVERLAY_ORB_STYLES } from '@shared/overlay-orb'

const picker = readFileSync(join(__dirname, './OverlayOrbPicker.tsx'), 'utf8')
const settings = readFileSync(join(__dirname, './Settings.tsx'), 'utf8')
const css = readFileSync(join(__dirname, '../styles.css'), 'utf8')
const thinking = readFileSync(join(__dirname, './JarvisOrbButton.tsx'), 'utf8')
const orb = readFileSync(join(__dirname, './ObsidianOrb.tsx'), 'utf8')
const bar = readFileSync(join(__dirname, './Bar.tsx'), 'utf8')
const pill = readFileSync(join(__dirname, './ControlPill.tsx'), 'utf8')
const design = readFileSync(join(__dirname, '../../../../docs/design/ORB-SELECTION.md'), 'utf8')

describe('Settings Bar rest orb cards', () => {
  it('renders Circle (default thinking-orb) and Jarvis (particles), never a Full Bar card', () => {
    expect(OVERLAY_ORB_STYLES).toEqual(['bar', 'jakub', 'obsidian'])
    expect(OVERLAY_ORB_PICKER_CARDS).toEqual(['jakub', 'obsidian'])
    expect(picker).toMatch(/aria-label="Bar rest"/)
    expect(picker).toMatch(/data-orb-diagram=\{id\}/)
    expect(picker).toMatch(/overlay-chrome-grid--two/)
    expect(picker).toMatch(/<JarvisOrbButton/)
    expect(picker).toMatch(/<ObsidianOrb/)
    expect(picker).toMatch(/preview/)
    expect(picker).toMatch(/animate=\{on\}/)
    expect(picker).toMatch(/data-orb-diagram-animate/)
    expect(thinking).toMatch(/overlay-orb-diagram__jakub--live/)
    expect(thinking).toMatch(/overlay-orb-diagram__jakub-host/)
    expect(picker).not.toMatch(/ThinkingOrb/)
    expect(picker).not.toMatch(/createJarvisOrb/)
    expect(picker).not.toMatch(/Full bar/)
    expect(picker).not.toMatch(/id === 'bar'/)
    expect(thinking).toMatch(/BrandThinkingOrb/)
    expect(thinking).toMatch(/<BrandThinkingOrb/)
    expect(thinking).not.toMatch(/from 'thinking-orbs'/)
    expect(thinking).toMatch(/if \(preview\)/)
    expect(thinking).toMatch(/data-orb-diagram-engine="thinking-orbs"/)
    expect(thinking).toMatch(/paintOrbFirstFrame/)
    expect(orb).toMatch(/if \(preview\)/)
    expect(orb).toMatch(/data-orb-engine="jarvis-particles"/)
    expect(orb).toMatch(/createJarvisOrb/)
    expect(settings).toMatch(/<OverlayOrbPicker/)
    expect(settings).toMatch(/overlayOrbStyle: id/)
    expect(settings).toMatch(/Applies when Overlay chrome is Bar/)
    expect(settings).toMatch(/overlayShowsBarRestPicker\(settings\.overlayLayout\)/)
    expect(css).toMatch(/\.overlay-chrome-grid--two/)
    expect(css).toMatch(/\.overlay-orb-diagram--jakub/)
    expect(css).toMatch(/\.overlay-orb-diagram,\n\.overlay-orb-diagram--jakub,[\s\S]*?height:\s*72px/)
    expect(css).toMatch(
      /\.overlay-orb-diagram--jakub \.overlay-orb-diagram__jakub--live \{[\s\S]*?width:\s*41px/
    )
    expect(css).toMatch(
      /\.overlay-orb-diagram--jakub \.overlay-orb-diagram__jakub--live \{[\s\S]*?overflow:\s*visible/
    )
    expect(css).toMatch(
      /\.overlay-orb-diagram--jakub \.overlay-orb-diagram__jakub--live \{[\s\S]*?background:\s*transparent/
    )
    expect(css).toMatch(/\.overlay-orb-diagram__jakub-host \{[\s\S]*?scale\(calc\(41 \/ 64\)\)/)
    expect(css).not.toMatch(/\.overlay-orb-diagram__jakub \{[\s\S]*?width:\s*22px/)
    expect(css).not.toMatch(/\.overlay-orb-diagram__jakub \{[\s\S]*?radial-gradient/)
    expect(css).toMatch(/\.circle-rest-spring--expand/)
    expect(css).toMatch(/@keyframes circle-rest-expand/)
    expect(css).not.toMatch(/\.overlay-orb-diagram--bar/)
    expect(css).toMatch(/\.obsidian-orb__canvas/)
    expect(css).not.toMatch(/\.obsidian-orb__spark/)
    expect(css).not.toMatch(/\.obsidian-orb__ring/)
    expect(orb).toMatch(/data-orb-style="obsidian"/)
    expect(orb).toMatch(/obsidian-orb__canvas/)
    expect(orb).not.toMatch(/obsidian-orb__spark/)
    expect(bar).toMatch(/overlayUsesJarvisOrb/)
    expect(bar).toMatch(/JarvisOrbButton/)
    expect(bar).toMatch(/<ObsidianOrb/)
    expect(pill).toMatch(/overlayUsesJarvisOrb/)
    expect(pill).toMatch(/JarvisOrbButton/)
    expect(pill).toMatch(/<ObsidianOrb/)
    expect(OVERLAY_ORB_COPY.jakub.title).toBe('Circle')
    expect(OVERLAY_ORB_COPY.obsidian.title).toBe('Jarvis')
    expect(OVERLAY_ORB_COPY.obsidian.desc).toMatch(/Particle sphere/)
    expect(picker).toMatch(/id === 'jakub' \? <span className="overlay-chrome-card__default">Default<\/span>/)
    expect(design).toMatch(/DESIGN before UI/)
    expect(design).toMatch(/0x4ca8e8/)
    expect(design).toMatch(/Circle/)
    expect(design).toMatch(/Never label it Obsidian|Never "Obsidian"/)
    expect(design).toMatch(/JarvisOrbButton/)
    expect(design).toMatch(/overlayShowsBarRestPicker/)
    expect(design).toMatch(/must \*\*not\*\* auto-minimize|must not auto-minimize/)
    const copy = Object.values(OVERLAY_ORB_COPY)
      .map((c) => `${c.title} ${c.desc}`)
      .join(' ')
    expect(copy).not.toMatch(/\u2014/)
    expect(copy).not.toMatch(/Obsidian/)
  })
})
